# documentation from sprint notes: 
# https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-172-update#generic-webhook-based-triggers-for-yaml-pipelines

# for more info on gotchas, see: 
# https://developercommunity.visualstudio.com/t/cannot-use-generic-webhook-based-triggers-for-yaml/1135943?viewtype=all

# NOTE: Pipeline has to be valid in order for webhook to fire

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  webhooks:
    - webhook: workitem          ### Webhook alias
      connection: workitem    ### Incoming webhook service connection
      # filters:
      #   - path: repositoryName      ### JSON path in the payload
      #     value: maven-releases     ### Expected value in the path provided
      #   - path: action
      #     value: CREATED
steps:
- bash: echo "hi"
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
    script: |
      write-host "Work item ID - ${{ parameters.workitem.resource.workItemId }}"
